#!/usr/bin/env python3
import os, subprocess

os.chdir(os.path.dirname(os.path.abspath(__file__)))

html_code = open("source.html").read()

procs = {
    "js": ["compile-js", "js/app.js", "js/date.js"],
    "css": ["compile-css", "css/main.css"],
}

for key in procs:
    procs[key] = subprocess.Popen(procs[key], stdout=subprocess.PIPE)

for key in procs:
    procs[key].wait()

for key in procs:
    compiled = procs[key].stdout.read().decode()
    if key == "js":
        html_code = html_code.replace("""<script src="js/app.js"></script>""", f"""<script>{compiled}</script>""").replace("""<script src="js/date.js"></script>""", '')
    elif key == "css":
        html_code = html_code.replace("""<link rel="stylesheet" type="text/css" href="css/main.css">""", f"""<style>{compiled}</style>""")

html_proc = subprocess.Popen(["html-minifier", "--collapse-whitespace"], stdout=subprocess.PIPE, stdin=subprocess.PIPE)
html_proc.stdin.write(html_code.encode())
html_proc.stdin.close()
html_proc.wait()
result = html_proc.stdout.read().decode()
open("index.html", "w").write(result)
